# -*- coding: utf-8 -*-
"""titanic-test2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dPNLO-45JZh_mor3buIKVJeqiWhBK2Er

#import library
"""

pip install pyforest

import pyforest

"""#read the dataset and controll"""

data=pd.read_csv('titanic.csv')

data.shape

data.info()

data.isnull().sum()

data.describe(include='all')

"""#drop!"""

data.drop(['Fare'],axis=1,inplace=True)
data.drop(['PassengerId'],axis=1,inplace=True)
data.drop(['Name'],axis=1,inplace=True)
data.drop(['SibSp'],axis=1,inplace=True)
data.drop(['Parch'],axis=1,inplace=True)
data.drop(['Ticket'],axis=1,inplace=True)
data.drop(['Cabin'],axis=1,inplace=True)
data.drop(['Embarked'],axis=1,inplace=True)

data.info()

"""#handle null value ( just age!)"""

data.isnull().sum()

data['Age'].fillna(data['Age'].mean(),inplace=True)

"""##Feature Engineering (One hot encoding)"""

data=pd.get_dummies(data, drop_first=True) #there is no class one
data.sample(7)

"""#split data & Train_test"""

X=data.drop('Survived',axis=1)
Y=data['Survived']

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, random_state=42, test_size=0.2)

"""#using the the model
#solver
"""

solver='lbfgs'
LogReg = LogisticRegression(solver=solver)
LogReg.fit(X_train,Y_train)

y_pred =LogReg.predict(X_test)

"""# Evaluate"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

accuracy = accuracy_score(Y_test, y_pred)
precision = precision_score(Y_test, y_pred)
recall = recall_score(Y_test, y_pred)
f1 = f1_score(Y_test, y_pred)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)